# Generated by Django 5.2.12 on 2026-04-06 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('user', 'quiz', 'live_session'), name='uniq_active_attempt_per_user_quiz_live'),
        ),
    ]
