# Generated by Django 5.2.12 on 2026-04-06 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_attempt_uniq_active_attempt_per_user_quiz_live'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attempt',
            name='uniq_active_attempt_per_user_quiz_live',
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('live_session__isnull', True), ('status', 'in_progress')), fields=('user', 'quiz'), name='uniq_active_attempt_per_user_quiz'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('live_session__isnull', False), ('status', 'in_progress')), fields=('user', 'quiz', 'live_session'), name='uniq_active_attempt_per_user_quiz_live'),
        ),
    ]
